services:
  postgres_db:
    image: postgres:15-alpine
    container_name: portfolio_postgres
    environment:
      - POSTGRES_DB=portfolio_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1527
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  auth_service:
    container_name: auth_service
    build:
      context: ./backend/AuthService
    environment:
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    depends_on:
      - postgres_db

  billing_service:
    container_name: billing_service
    build:
      context: ./backend/BillingService
    environment:
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    depends_on:
      - postgres_db

  analysis_service:
    container_name: analysis_service
    build:
      context: ./backend/analysis_service
    restart: unless-stopped

  api_gateway:
    container_name: api_gateway
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - auth_service
      - billing_service
      - analysis_service

volumes:
  postgres_data: